### ISSUE TITLE
Reset simulation screw world up

### ISSUE THREAD

**Issue by deePurrobotics** [deePurrobotics/gazebo_rl#1]
may need change reset simulation to reset world

**Comment by linZHank** [comment]
If world was created in gazebo GUI and saved afterward, there will be a block of `<state>` description in your `.world` file. delete this part, and edit models according to your need.

**Comment by linZHank** [comment]
According to this [tutorial](http://gazebosim.org/tutorials?tut=drcsim_modify_world&cat=), loading a world that contains <state> tags is not working properly. Thus, you must also delete the <state> tag and all its child elements (everything from <state> until </state>)
